"""renamed the table lecture note to course note and change content type to resource type

Revision ID: 033c523cc3e8
Revises: 6ed1db905fc8
Create Date: 2026-09-25 13:28:07.655204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '033c523cc3e8'
down_revision: Union[str, Sequence[str], None] = '6ed1db905fc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("lecture_note", "course_note")
    with op.batch_alter_table("course_note", schema =None) as batch_op:
        batch_op.alter_column("content_type", new_column_name="resource_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.rename_table("course_note", "lecture_note")
    with op.batch_alter_table("lecture_note", schema =None) as batch_op:
            batch_op.alter_column("resource_type", new_column_name="content_type")
    
    # ### end Alembic commands ###
