"""Updated the thread

Revision ID: 1c7cc2ef56d8
Revises: ab60b51bb3c3
Create Date: 2026-10-06 15:53:40.950163

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1c7cc2ef56d8"
down_revision: Union[str, Sequence[str], None] = "ab60b51bb3c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("thread", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("thread_course_id_fkey"), type_="foreignkey"
        )
        batch_op.drop_column("course_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("thread", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("course_id", sa.UUID(), autoincrement=False, nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f("thread_course_id_fkey"), "course", ["course_id"], ["id"]
        )

    # ### end Alembic commands ###
