"""Updated delete for thread and user id

Revision ID: 41154975a682
Revises: a1030292b3dc
Create Date: 2026-09-25 15:43:29.594384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41154975a682'
down_revision: Union[str, Sequence[str], None] = 'a1030292b3dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('thread', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('thread_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key("thread_user_id_fkey", 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thread', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint("thread_user_id_fkey", type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('thread_user_id_fkey'), 'user', ['user_id'], ['id'])



    # ### end Alembic commands ###
