"""Added/Updated course related models

Revision ID: 4d13e94a22d2
Revises: 624c876f127a
Create Date: 2026-09-22 16:16:58.870997

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4d13e94a22d2'
down_revision: str | Sequence[str] | None = '624c876f127a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_access_code',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('code_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_access_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_access_code_code_hash'), ['code_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_course_access_code_course_id'), ['course_id'], unique=False)

    op.create_table('course_enrollment',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'course_id'),
    sa.UniqueConstraint('student_id', 'course_id', name='uq_course_enrollment_student_id')
    )
    op.drop_table('studentcourselink')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Uuid(), nullable=False))
        batch_op.add_column(sa.Column('storage_prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('discipline',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_course_owner_id'), ['owner_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_owner_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_course_owner_id_user', 'user', ['owner_id'], ['id'])
        batch_op.drop_column('blob')
        batch_op.drop_column('owner')

    with op.batch_alter_table('lecturenote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('file_size_bytes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.create_unique_constraint("uq_storage_path", ['storage_path'])
        batch_op.drop_column('file_url')
        batch_op.drop_column('file_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecturenote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint('uq_storage_path', type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('file_size_bytes')
        batch_op.drop_column('content_type')
        batch_op.drop_column('storage_path')
        batch_op.drop_column('original_filename')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('blob', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint('fk_course_owner_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_owner_id_user'), 'user', ['owner'], ['id'])
        batch_op.drop_index(batch_op.f('ix_course_owner_id'))
        batch_op.alter_column('discipline',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('storage_prefix')
        batch_op.drop_column('owner_id')

    op.create_table('studentcourselink',
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('studentcourselink_course_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('studentcourselink_student_id_fkey')),
    sa.PrimaryKeyConstraint('student_id', 'course_id', name=op.f('studentcourselink_pkey'))
    )
    op.drop_table('course_enrollment')
    with op.batch_alter_table('course_access_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_access_code_course_id'))
        batch_op.drop_index(batch_op.f('ix_course_access_code_code_hash'))

    op.drop_table('course_access_code')
    # ### end Alembic commands ###
