"""Updated user table removed fields and updated the role model to use enum values

Revision ID: 624c876f127a
Revises: 4075a377d0fa
Create Date: 2026-09-22 12:29:31.253831

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "624c876f127a"
down_revision: str | Sequence[str] | None = "4075a377d0fa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

user_role_enum = sa.Enum(
    "STUDENT",
    "EDUCATOR",
    "ADMIN",
    name="user_role",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    rows = op.get_bind().execute(sa.text("SELECT id, name FROM role")).mappings().all()
    # Old value->New Value mapping
    role_map = {
        "STUDENT": "STUDENT",
        "EDUCATOR": "EDUCATOR",
        "ADMIN": "ADMIN",
        "student": "STUDENT",
        "educator": "EDUCATOR",
        "admin": "ADMIN",
    }
    # Normalize the rows and update the name
    for row in rows:
        normalized = role_map.get(row["name"])
        if normalized is None:
            raise ValueError(f"Unknown role value: {row['name']}")
        op.get_bind().execute(
            sa.text("UPDATE role SET name=:name WHERE id = :id"),
            {"name": normalized, "id": row["id"]},
        )
    # Create the enum table
    user_role_enum.create(op.get_bind(), checkfirst=True)
    op.rename_table("userrolelink", "user_role_link")
    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.VARCHAR(),
            type_=user_role_enum,
            existing_nullable=False,
            postgresql_using="name::user_role",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.Enum("STUDENT", "EDUCATOR", "ADMIN", name="user_role"),
            type_=sa.VARCHAR(),
            existing_nullable=False,
            postgresql_using="name::text",
        )
    user_role_enum.drop(op.get_bind(), checkfirst=True)
    op.rename_table("user_role_link", "userrolelink")
    # ### end Alembic commands ###
