"""Updated lecture note model to be more of a link table including enums for resource type and updated file model

Revision ID: 6ed1db905fc8
Revises: 859017df8b79
Create Date: 2026-09-25 13:17:48.887719

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6ed1db905fc8"
down_revision: Union[str, Sequence[str], None] = "859017df8b79"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


"""Updated lecture note model to be more of a link table including enums for resource type

Revision ID: 87152f0e7440
Revises: 859017df8b79
Create Date: 2026-09-25 13:04:09.521235

"""


content_type_enum = sa.Enum(
    "LECTURE",
    "NOTES",
    "ASSIGNMENT",
    "EXAM",
    "QUIZ",
    "TEXTBOOK",
    "HANDOUT",
    "SYLLABUS",
    "REFERENCE",
    "OTHER",
    name="course_content_type",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.drop_constraint("file_pkey", type_="primary")
        batch_op.alter_column("id", existing_type=sa.UUID(), nullable=False)
        batch_op.create_primary_key("file_pkey", ["id"])
        batch_op.create_index(batch_op.f("ix_file_owner_id"), ["owner_id"], unique=False)

    content_type_enum.create(op.get_bind(), checkfirst=True)

    # Handle conversion
    rows = (
        op.get_bind()
        .execute(sa.text("SELECT id, content_type FROM lecture_note"))
        .mappings()
        .all()
    )
    for row in rows:
        op.get_bind().execute(
            sa.text(
                "UPDATE lecture_note SET content_type=:content_type WHERE id = :id"
            ),
            {"content_type": "OTHER", "id": row["id"]},
        )
    with op.batch_alter_table("lecture_note", schema=None) as batch_op:
        batch_op.add_column(sa.Column("file_id", sa.Uuid(), nullable=False))
        batch_op.alter_column(
            "content_type",
            existing_type=sa.VARCHAR(),
            type_=content_type_enum,
            nullable=False,
            postgresql_using="content_type::course_content_type",
        )
        batch_op.drop_constraint(batch_op.f("uq_storage_path"), type_="unique")
        batch_op.create_foreign_key(
            "fk-file_id", "file", ["file_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.drop_column("updated_at")
        batch_op.drop_column("original_filename")
        batch_op.drop_column("storage_path")
        batch_op.drop_column("uploaded_at")
        batch_op.drop_column("file_size_bytes")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lecture_note", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "file_size_bytes", sa.INTEGER(), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "uploaded_at",
                postgresql.TIMESTAMP(),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("storage_path", sa.VARCHAR(), autoincrement=False, nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "original_filename", sa.VARCHAR(), autoincrement=False, nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "updated_at",
                postgresql.TIMESTAMP(),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_constraint("fk-file_id", type_="foreignkey")
        batch_op.create_unique_constraint(
            batch_op.f("uq_storage_path"),
            ["storage_path"],
            postgresql_nulls_not_distinct=False,
        )
        batch_op.alter_column(
            "content_type",
            existing_type=content_type_enum,
            type_=sa.VARCHAR(),
            nullable=True,
        )
        batch_op.drop_column("file_id")
    content_type_enum.drop(op.get_bind(), checkfirst=True)

    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_file_owner_id"))
        batch_op.alter_column("id", existing_type=sa.UUID(), nullable=True)

    # ### end Alembic commands ###
