"""updated lecture note table name

Revision ID: 905eeefcccae
Revises: 4d13e94a22d2
Create Date: 2026-09-22 16:19:49.203484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '905eeefcccae'
down_revision: Union[str, Sequence[str], None] = '4d13e94a22d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.rename_table('lecturenote', "lecture_note")


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('lecture_note', "lecturenote")
   
    # ### end Alembic commands ###
