"""updated lecture note table name

Revision ID: 905eeefcccae
Revises: 4d13e94a22d2
Create Date: 2026-09-22 16:19:49.203484

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '905eeefcccae'
down_revision: str | Sequence[str] | None = '4d13e94a22d2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.rename_table('lecturenote', "lecture_note")


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('lecture_note', "lecturenote")
   
    # ### end Alembic commands ###
