"""Initial migration

Revision ID: 9d5b6447e665
Revises:
Create Date: 2026-02-17 13:49:45.311412

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "9d5b6447e665"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
