"""Updated delete for user role link

Revision ID: a1030292b3dc
Revises: f672ef47219d
Create Date: 2026-09-25 15:41:27.646470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1030292b3dc'
down_revision: Union[str, Sequence[str], None] = 'f672ef47219d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('user_role_link', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('userrolelink_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key("userrolelink_user_id_fkey", 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_role_link', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint("userrolelink_user_id_fkey", type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('userrolelink_user_id_fkey'), 'user', ['user_id'], ['id'])


    # ### end Alembic commands ###
