"""Added course module

Revision ID: ab60b51bb3c3
Revises: 41154975a682
Create Date: 2026-10-01 15:45:21.695171

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ab60b51bb3c3"
down_revision: Union[str, Sequence[str], None] = "41154975a682"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


STATUS_ENUM = sa.Enum("DRAFT", "PUBLIC", name="status")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course_module",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["course_id"], ["course.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("course_id", "id", name="uq_course_module_course_id"),
    )
    STATUS_ENUM.create(op.get_bind(), checkfirst=True)
    with op.batch_alter_table("course_module", schema=None) as batch_op:
        batch_op.create_index(
            "ix_course_modules_course_position", ["course_id", "position"], unique=False
        )

    with op.batch_alter_table("course_note", schema=None) as batch_op:
        batch_op.add_column(sa.Column("status", STATUS_ENUM, nullable=True))

    op.get_bind().execute(sa.text("UPDATE course_note SET status='DRAFT'"))
    with op.batch_alter_table("course_note", schema=None) as batch_op:
        batch_op.alter_column("status", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("course_note", schema=None) as batch_op:

        batch_op.drop_column("status")

    with op.batch_alter_table("course_module", schema=None) as batch_op:
        batch_op.drop_index("ix_course_modules_course_position")

    op.drop_table("course_module")
    STATUS_ENUM.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
