"""Updated course model added blob

Revision ID: b96abc282e1b
Revises: 9d5b6447e665
Create Date: 2026-02-17 13:51:15.381262

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "b96abc282e1b"
down_revision: Union[str, Sequence[str], None] = "9d5b6447e665"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "course", sa.Column("blob", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("course", "blob")
    # ### end Alembic commands ###
