"""Updated course model added blob

Revision ID: b96abc282e1b
Revises: 9d5b6447e665
Create Date: 2026-02-17 13:51:15.381262

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import context
from alembic import op
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = "b96abc282e1b"
down_revision: str | Sequence[str] | None = "9d5b6447e665"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    
    if context.is_offline_mode():
        print("Skipping inspection in offline mode")
        return
    bind = op.get_bind()
    inspector = inspect(bind)

    columns = [c["name"] for c in inspector.get_columns("user")]

    print("\n=== USER COLUMNS ===")
    for col in inspector.get_columns("user"):
        print(col["name"], col["type"])

    if "username" not in columns:
        op.add_column(
            "user",
            sa.Column("username", sa.String(), nullable=True),
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("course", "blob")
    # ### end Alembic commands ###
