"""Added the student course link

Revision ID: eb65a3e7967a
Revises: b96abc282e1b
Create Date: 2026-02-17 15:17:15.494407

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eb65a3e7967a"
down_revision: Union[str, Sequence[str], None] = "b96abc282e1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

naming_convention = {
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "course", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.create_foreign_key("fk_owner_id_user", "user", ["owner"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "course", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.drop_constraint("fk_owner_id_user", type_="foreignkey")

    # ### end Alembic commands ###
