"""Check

Revision ID: f672ef47219d
Revises: 033c523cc3e8
Create Date: 2026-09-25 14:16:16.637933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f672ef47219d'
down_revision: Union[str, Sequence[str], None] = '033c523cc3e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('storage_prefix')

    with op.batch_alter_table('course_note', schema=None) as batch_op:
        batch_op.alter_column('resource_type',
               existing_type=postgresql.ENUM('LECTURE', 'NOTES', 'ASSIGNMENT', 'EXAM', 'QUIZ', 'TEXTBOOK', 'HANDOUT', 'SYLLABUS', 'REFERENCE', 'OTHER', name='course_content_type'),
               type_=sa.Enum('LECTURE', 'NOTES', 'ASSIGNMENT', 'EXAM', 'QUIZ', 'TEXTBOOK', 'HANDOUT', 'SYLLABUS', 'REFERENCE', 'OTHER', name='course_content_type'),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_course_note_course_file', ['course_id', 'file_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_note', schema=None) as batch_op:
        batch_op.drop_constraint('uq_course_note_course_file', type_='unique')
        batch_op.alter_column('resource_type',
               existing_type=sa.Enum('LECTURE', 'NOTES', 'ASSIGNMENT', 'EXAM', 'QUIZ', 'TEXTBOOK', 'HANDOUT', 'SYLLABUS', 'REFERENCE', 'OTHER', name='course_content_type'),
               type_=postgresql.ENUM('LECTURE', 'NOTES', 'ASSIGNMENT', 'EXAM', 'QUIZ', 'TEXTBOOK', 'HANDOUT', 'SYLLABUS', 'REFERENCE', 'OTHER', name='course_content_type'),
               existing_nullable=False)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_prefix', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
